### ISSUE TITLE
Library doesn't load obj file exported from Blender

### ISSUE THREAD

**Issue by dblsaiko** [zesterer/wavefront#3]
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidIndex(143)'

143 is the highest vertex index in the file, off-by-one error?

The file in question: [scene.obj][1]

[1]: https://paste.2x.ax/~saiko/846d938ae77184b419143771327aba7169c66c61

**Comment by zesterer** [comment]
I've just released version `0.2.2` with this change.
